name: Trigger auto deployment for audit-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ config/azure-cicd ]
    paths:
    - '**'
    - '.github/workflows/audit-service-AutoDeployTrigger-dd8f26a2-06e4-4c60-aad6-9ea4f8d9d7b7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AUDITSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUDITSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUDITSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrsmarttaskmanagersea.azurecr.io
          registryUsername: ${{ secrets.AUDITSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUDITSERVICE_REGISTRY_PASSWORD }}
          containerAppName: audit-service
          resourceGroup: rg-smart-task-manager-sea
          imageToBuild: acrsmarttaskmanagersea.azurecr.io/audit-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


