name: Trigger auto deployment for client

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ config/azure-cicd ]
    paths:
    - '**'
    - '.github/workflows/client-AutoDeployTrigger-9aa01220-acbf-43ac-8b64-bcff7262cf6a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLIENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLIENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/client
          dockerfilePath: Dockerfile
          registryUrl: acrsmarttaskmanagersea.azurecr.io
          registryUsername: ${{ secrets.CLIENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLIENT_REGISTRY_PASSWORD }}
          containerAppName: client
          resourceGroup: rg-smart-task-manager-sea
          imageToBuild: acrsmarttaskmanagersea.azurecr.io/client:${{ github.sha }}
          buildArguments: VITE_API_BASE_URL=https://api-gateway.jollycoast-3e03ff25.southeastasia.azurecontainerapps.io


