name: Trigger auto deployment for report-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ config/azure-cicd ]
    paths:
    - '**'
    - '.github/workflows/report-service-AutoDeployTrigger-f8fa0c0d-5261-4fba-b79e-d067dc0776f4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.REPORTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REPORTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REPORTSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/report-service
          dockerfilePath: Dockerfile
          
          registryUrl: acrsmarttaskmanagersea.azurecr.io
          registryUsername: ${{ secrets.REPORTSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REPORTSERVICE_REGISTRY_PASSWORD }}
          containerAppName: report-service
          resourceGroup: rg-smart-task-manager-sea
          imageToBuild: acrsmarttaskmanagersea.azurecr.io/report-service:${{ github.sha }}
          
            


